export interface PackageType {
  id: number;
  name: string;
}

export const packageTypeOptions: PackageType[] = [
  { id: 1, name: "D CONTAINER" },
  { id: 2, name: "TYPE L-N" },
  { id: 3, name: "TYPE EH" },
  { id: 4, name: "TYPE E" },
  { id: 5, name: "LD-2 (IATA TYPE 8D)" },
  { id: 6, name: "LD-3 (IATA TYPE 8)" },
  { id: 7, name: "LD-4 (IATA TYPE 7A)" },
  { id: 8, name: "LD-8 ( IATA TYPE 6A)" },
  { id: 9, name: "LD-11 (IATA TYPE 6)" },
  { id: 10, name: "LD-11 PALLET (IATA TYPE 6)" },
  { id: 11, name: "LD-7 (IATA TYPE 5)" },
  { id: 41, name: "UNIT 2" },
  { id: 42, name: "VAN PACK" },
  { id: 43, name: "UNIT" },
  { id: 44, name: "TIN" },
  { id: 45, name: "TOTE BIN" },
  { id: 46, name: "REEL" },
  { id: 47, name: "PRIVATELY OWNED VEHICLE" },
  { id: 48, name: "PAIL" },
  { id: 49, name: "LIFT VAN" },
  { id: 50, name: "LUG" },
  { id: 51, name: "LOG" },
  { id: 52, name: "LIQUID BULK" },
  { id: 53, name: "KEG" },
  { id: 54, name: "HAMPER" },
  { id: 55, name: "HEAD OF BEEF" },
  { id: 56, name: "DRY BULK" },
  { id: 57, name: "CARTON" },
  { id: 58, name: "CASK" },
  { id: 59, name: "CORD" },
  { id: 60, name: "COIL" },
  { id: 61, name: "CHEST" },
  { id: 62, name: "CAN CASE" },
  { id: 63, name: "CARBOY" },
  { id: 64, name: "CONTAINER BULK CARGO" },
  { id: 65, name: "CASE" },
  { id: 66, name: "CARCASS" },
  { id: 67, name: "CAN" },
  { id: 68, name: "BALE" },
  { id: 69, name: "BUCKET" },
  { id: 70, name: "BIN" },
  { id: 71, name: "BING CHEST" },
  { id: 72, name: "BUNDLE" },
  { id: 73, name: "WRAPPED" },
  { id: 74, name: "VEHICLES" },
  { id: 75, name: "TRAY" },
  { id: 76, name: "TUBE" },
  { id: 77, name: "SHEET" },
  { id: 78, name: "ROLL" },
  { id: 79, name: "RACK" },
  { id: 80, name: "PACKAGE" },
  { id: 81, name: "PIECES" },
  { id: 82, name: "PARCEL" },
  { id: 83, name: "GALLON" },
  { id: 84, name: "FRAME" },
  { id: 85, name: "ENVELOPE" },
  { id: 86, name: "CYLINDER" },
  { id: 87, name: "CONES" },
  { id: 88, name: "CABINET" },
  { id: 89, name: "BASKET" },
  { id: 90, name: "BOTTLE" },
  { id: 91, name: "BARREL" },
  { id: 92, name: "CRATE" },
  { id: 93, name: "TANK" },
  { id: 94, name: "SKID" },
  { id: 95, name: "DRUM" },
  { id: 96, name: "BAG" },
  { id: 97, name: "BOX" },
  { id: 98, name: "PALLET" },
  { id: 99, name: "OTHER" },
  { id: 100, name: "CONTAINER" },
  { id: 101, name: "40 NOR" },
  { id: 102, name: "FALSO SIDER 13,5 MTS" },
  { id: 103, name: "FALSO SIDER 14,5 MTS" },
  { id: 104, name: "FALSO SIDER 15,5 MTS" },
  { id: 105, name: "PORTA CONTENEDOR DE 40" },
  { id: 106, name: "RAMPLA CORTA DE 20" },
  { id: 107, name: "CAMION BAUL REEFER DE 40" },
  { id: 108, name: "CAMION CAMA BAJA" },
  { id: 109, name: "CAMION GRÚA" },
  { id: 110, name: "CARGA GENERAL" },
];
