/**
 * Datos dummy de ocean-shipments exclusivos para la cuenta MundoGaming.
 * Estas operaciones son ficticias y no afectan KPIs ni datos reales de Linbis.
 */

import type { OceanShipment } from "./Handleroceanshipments";

export const MUNDOGAMING_DUMMY_OCEAN_SHIPMENTS: OceanShipment[] = [
  // ── Operación 1: En tránsito (LCL – salió, aún no llega) ──
  {
    id: 80001,
    number: "HBLI0008001",
    operationFlow: "Import",
    shipmentType: "Ocean",
    currentFlow: "In Transit",
    departure: "2026-01-25T04:00:00Z",
    arrival: "2026-03-05T04:00:00Z",
    portOfLoading: "PUERTO DE SHANGHAI",
    portOfUnloading: "SAN ANTONIO",
    placeOfDelivery: "Santiago, Chile",
    vessel: "MAERSK EDINBURGH",
    voyage: "402S",
    carrier: "MAERSK CHILE S.A.",
    bookingNumber: "MGO-BK-2026-001",
    waybillNumber: "(H)EURFL26A05210SAI",
    containerNumber: "MSKU7823456",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "SHENZHEN TECHZONE ELECTRONICS CO., LTD",
    shipperAddress:
      "SHENZHEN TECHZONE ELECTRONICS CO., LTD\nBLOCK A, 3/F, NO.18 KEYUAN RD, NANSHAN DISTRICT\n518000, SHENZHEN, GUANGDONG, CHINA",
    customerReference: "TECHZONE OC 20500",
    cargoDescription: "STC: GAMING CONSOLES & ACCESSORIES",
    typeOfMove: "LCL",
    totalCargo_Pieces: 12,
    totalCargo_WeightDisplayValue: "1,850.00 kg",
    totalCargo_VolumeDisplayValue: "8.200 m³",
    createdOn: "2026-01-20T15:30:00Z",
    hazardous: false,
    containerized: true,
    customsReleased: false,
    freightReleased: false,
  },

  // ── Operación 2: Ya arribó (FCL – llegó al puerto) ──
  {
    id: 80002,
    number: "HBLI0008002",
    operationFlow: "Import",
    shipmentType: "Ocean",
    currentFlow: "Arrived",
    departure: "2025-12-15T04:00:00Z",
    arrival: "2026-01-28T04:00:00Z",
    portOfLoading: "PUERTO DE NINGBO",
    portOfUnloading: "VALPARAISO",
    placeOfDelivery: "Santiago, Chile",
    vessel: "MSC LORENA",
    voyage: "FL601W",
    carrier: "MSC MEDITERRANEAN SHIPPING",
    bookingNumber: "MGO-BK-2025-042",
    waybillNumber: "(H)MSCFL25L12480VLP",
    containerNumber: "MSCU9012345",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "DONGGUAN PIXELGEAR TECHNOLOGY CO., LTD",
    shipperAddress:
      "DONGGUAN PIXELGEAR TECHNOLOGY CO., LTD\nNO.88 DONGCHENG SOUTH RD, DONGCHENG DISTRICT\n523000, DONGGUAN, GUANGDONG, CHINA",
    customerReference: "PIXELGEAR OC 8550 / TECHZONE OC 20410",
    cargoDescription: "STC: GAMING MONITORS, LED PANELS, CONTROLLERS",
    typeOfMove: "FCL",
    totalCargo_Pieces: 45,
    totalCargo_WeightDisplayValue: "4,320.00 kg",
    totalCargo_VolumeDisplayValue: "28.500 m³",
    createdOn: "2025-12-10T12:00:00Z",
    hazardous: false,
    containerized: true,
    customsReleased: false,
    freightReleased: false,
  },

  // ── Operación 3: En tránsito (LCL) ──
  {
    id: 80003,
    number: "HBLI0008003",
    operationFlow: "Import",
    shipmentType: "Ocean",
    currentFlow: "In Transit",
    departure: "2026-02-01T04:00:00Z",
    arrival: "2026-03-10T04:00:00Z",
    portOfLoading: "PUERTO DE QINGDAO",
    portOfUnloading: "SAN ANTONIO",
    placeOfDelivery: "Santiago, Chile",
    vessel: "CMA CGM FORTUNE",
    voyage: "0FL601W",
    carrier: "CMA CGM CHILE S.A.",
    bookingNumber: "MGO-BK-2026-003",
    waybillNumber: "(H)CMFL26A05211SAI",
    containerNumber: "CMAU3456789",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "SHENZHEN GAMING ELECTRONICS CO., LTD",
    shipperAddress:
      "SHENZHEN GAMING ELECTRONICS CO., LTD\nBLOCK B, 4/F, NO.19 KEYUAN RD, NANSHAN DISTRICT\n518000, SHENZHEN, GUANGDONG, CHINA",
    customerReference: "GAMING OC 20501",
    cargoDescription: "STC: GAMING LAPTOPS & HIGH-END PCS",
    typeOfMove: "LCL",
    totalCargo_Pieces: 8,
    totalCargo_WeightDisplayValue: "1,200.00 kg",
    totalCargo_VolumeDisplayValue: "6.500 m³",
    createdOn: "2026-01-25T14:45:00Z",
    hazardous: false,
    containerized: true,
    customsReleased: false,
    freightReleased: false,
  },

  // ── Operación 4: Ya arribó (FCL) ──
  {
    id: 80004,
    number: "HBLI0008004",
    operationFlow: "Import",
    shipmentType: "Ocean",
    currentFlow: "Arrived",
    departure: "2025-12-20T04:00:00Z",
    arrival: "2026-02-02T04:00:00Z",
    portOfLoading: "PUERTO DE TIANJIN",
    portOfUnloading: "VALPARAISO",
    placeOfDelivery: "Santiago, Chile",
    vessel: "EVER GREEN",
    voyage: "FL602W",
    carrier: "EVERGREEN LINE",
    bookingNumber: "MGO-BK-2025-043",
    waybillNumber: "(H)EVFL25L12481VLP",
    containerNumber: "EGHU5678901",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "DONGGUAN PROGAMING TECH CO., LTD",
    shipperAddress:
      "DONGGUAN PROGAMING TECH CO., LTD\nNO.89 DONGCHENG SOUTH RD, DONGCHENG DISTRICT\n523000, DONGGUAN, GUANGDONG, CHINA",
    customerReference: "PROGAMING OC 8551",
    cargoDescription: "STC: GAMING CHAIRS & ERGONOMIC DESKS",
    typeOfMove: "FCL",
    totalCargo_Pieces: 30,
    totalCargo_WeightDisplayValue: "3,500.00 kg",
    totalCargo_VolumeDisplayValue: "22.000 m³",
    createdOn: "2025-12-15T10:30:00Z",
    hazardous: false,
    containerized: true,
    customsReleased: false,
    freightReleased: false,
  },

  // ── Operación 5: En tránsito (LCL) ──
  {
    id: 80005,
    number: "HBLI0008005",
    operationFlow: "Import",
    shipmentType: "Ocean",
    currentFlow: "In Transit",
    departure: "2026-02-05T04:00:00Z",
    arrival: "2026-03-15T04:00:00Z",
    portOfLoading: "PUERTO DE SHANGHAI",
    portOfUnloading: "SAN ANTONIO",
    placeOfDelivery: "Santiago, Chile",
    vessel: "MSC ARIANE",
    voyage: "FL603W",
    carrier: "MSC MEDITERRANEAN SHIPPING",
    bookingNumber: "MGO-BK-2026-004",
    waybillNumber: "(H)MSCFL26A05212SAI",
    containerNumber: "MSCU4567890",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "SHENZHEN VRZONE ELECTRONICS CO., LTD",
    shipperAddress:
      "SHENZHEN VRZONE ELECTRONICS CO., LTD\nBLOCK C, 5/F, NO.20 KEYUAN RD, NANSHAN DISTRICT\n518000, SHENZHEN, GUANGDONG, CHINA",
    customerReference: "VRZONE OC 20502",
    cargoDescription: "STC: VR HEADSETS & IMMERSION DEVICES",
    typeOfMove: "LCL",
    totalCargo_Pieces: 15,
    totalCargo_WeightDisplayValue: "950.00 kg",
    totalCargo_VolumeDisplayValue: "4.800 m³",
    createdOn: "2026-01-30T16:20:00Z",
    hazardous: false,
    containerized: true,
    customsReleased: false,
    freightReleased: false,
  },

  // ── Operación 6: Ya arribó (FCL) ──
  {
    id: 80006,
    number: "HBLI0008006",
    operationFlow: "Import",
    shipmentType: "Ocean",
    currentFlow: "Arrived",
    departure: "2025-12-25T04:00:00Z",
    arrival: "2026-02-08T04:00:00Z",
    portOfLoading: "PUERTO DE NINGBO",
    portOfUnloading: "VALPARAISO",
    placeOfDelivery: "Santiago, Chile",
    vessel: "MAERSK HAMBURG",
    voyage: "403S",
    carrier: "MAERSK CHILE S.A.",
    bookingNumber: "MGO-BK-2025-044",
    waybillNumber: "(H)EURFL25L12482VLP",
    containerNumber: "MSKU8901234",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "DONGGUAN STREAMTECH CO., LTD",
    shipperAddress:
      "DONGGUAN STREAMTECH CO., LTD\nNO.90 DONGCHENG SOUTH RD, DONGCHENG DISTRICT\n523000, DONGGUAN, GUANGDONG, CHINA",
    customerReference: "STREAMTECH OC 8552",
    cargoDescription: "STC: STREAMING EQUIPMENT & WEBCAMS",
    typeOfMove: "FCL",
    totalCargo_Pieces: 50,
    totalCargo_WeightDisplayValue: "2,800.00 kg",
    totalCargo_VolumeDisplayValue: "18.500 m³",
    createdOn: "2025-12-20T11:15:00Z",
    hazardous: false,
    containerized: true,
    customsReleased: false,
    freightReleased: false,
  },

  // ── Operación 7: En tránsito (LCL) ──
  {
    id: 80007,
    number: "HBLI0008007",
    operationFlow: "Import",
    shipmentType: "Ocean",
    currentFlow: "In Transit",
    departure: "2026-02-08T04:00:00Z",
    arrival: "2026-03-20T04:00:00Z",
    portOfLoading: "PUERTO DE QINGDAO",
    portOfUnloading: "SAN ANTONIO",
    placeOfDelivery: "Santiago, Chile",
    vessel: "COSCO SHIPPING LEO",
    voyage: "FL604W",
    carrier: "COSCO SHIPPING LINES",
    bookingNumber: "MGO-BK-2026-005",
    waybillNumber: "(H)COSFL26A05213SAI",
    containerNumber: "COSU6789012",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "SHENZHEN CONSOLE TECH CO., LTD",
    shipperAddress:
      "SHENZHEN CONSOLE TECH CO., LTD\nBLOCK D, 6/F, NO.21 KEYUAN RD, NANSHAN DISTRICT\n518000, SHENZHEN, GUANGDONG, CHINA",
    customerReference: "CONSOLE OC 20503",
    cargoDescription: "STC: NEXT-GEN GAMING CONSOLES",
    typeOfMove: "LCL",
    totalCargo_Pieces: 20,
    totalCargo_WeightDisplayValue: "1,600.00 kg",
    totalCargo_VolumeDisplayValue: "9.200 m³",
    createdOn: "2026-02-02T13:40:00Z",
    hazardous: false,
    containerized: true,
    customsReleased: false,
    freightReleased: false,
  },

  // ── Operación 8: Ya arribó (FCL) ──
  {
    id: 80008,
    number: "HBLI0008008",
    operationFlow: "Import",
    shipmentType: "Ocean",
    currentFlow: "Arrived",
    departure: "2026-01-02T04:00:00Z",
    arrival: "2026-02-12T04:00:00Z",
    portOfLoading: "PUERTO DE SHANGHAI",
    portOfUnloading: "VALPARAISO",
    placeOfDelivery: "Santiago, Chile",
    vessel: "HMM ALGECIRAS",
    voyage: "FL605W",
    carrier: "HYUNDAI MERCHANT MARINE",
    bookingNumber: "MGO-BK-2026-006",
    waybillNumber: "(H)HMMFL26L12483VLP",
    containerNumber: "HMMU2345678",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "DONGGUAN LIGHTING PRO CO., LTD",
    shipperAddress:
      "DONGGUAN LIGHTING PRO CO., LTD\nNO.91 DONGCHENG SOUTH RD, DONGCHENG DISTRICT\n523000, DONGGUAN, GUANGDONG, CHINA",
    customerReference: "LIGHTING OC 8553",
    cargoDescription: "STC: RGB LIGHTING & LED CONTROLLERS",
    typeOfMove: "FCL",
    totalCargo_Pieces: 40,
    totalCargo_WeightDisplayValue: "3,200.00 kg",
    totalCargo_VolumeDisplayValue: "25.000 m³",
    createdOn: "2025-12-28T09:50:00Z",
    hazardous: false,
    containerized: true,
    customsReleased: false,
    freightReleased: false,
  },

  // ── Operación 9: En tránsito (LCL) ──
  {
    id: 80009,
    number: "HBLI0008009",
    operationFlow: "Import",
    shipmentType: "Ocean",
    currentFlow: "In Transit",
    departure: "2026-02-10T04:00:00Z",
    arrival: "2026-03-25T04:00:00Z",
    portOfLoading: "PUERTO DE NINGBO",
    portOfUnloading: "SAN ANTONIO",
    placeOfDelivery: "Santiago, Chile",
    vessel: "ONE HONG KONG",
    voyage: "FL606W",
    carrier: "OCEAN NETWORK EXPRESS",
    bookingNumber: "MGO-BK-2026-007",
    waybillNumber: "(H)ONEFL26A05214SAI",
    containerNumber: "ONEY8901234",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "SHENZHEN AUDIO PRO CO., LTD",
    shipperAddress:
      "SHENZHEN AUDIO PRO CO., LTD\nBLOCK E, 7/F, NO.22 KEYUAN RD, NANSHAN DISTRICT\n518000, SHENZHEN, GUANGDONG, CHINA",
    customerReference: "AUDIO OC 20504",
    cargoDescription: "STC: GAMING SPEAKERS & AUDIO SYSTEMS",
    typeOfMove: "LCL",
    totalCargo_Pieces: 18,
    totalCargo_WeightDisplayValue: "1,400.00 kg",
    totalCargo_VolumeDisplayValue: "7.800 m³",
    createdOn: "2026-02-05T15:10:00Z",
    hazardous: false,
    containerized: true,
    customsReleased: false,
    freightReleased: false,
  },

  // ── Operación 10: Ya arribó (FCL) ──
  {
    id: 80010,
    number: "HBLI0008010",
    operationFlow: "Import",
    shipmentType: "Ocean",
    currentFlow: "Arrived",
    departure: "2026-01-05T04:00:00Z",
    arrival: "2026-02-15T04:00:00Z",
    portOfLoading: "PUERTO DE TIANJIN",
    portOfUnloading: "VALPARAISO",
    placeOfDelivery: "Santiago, Chile",
    vessel: "PIL EXPRESS",
    voyage: "FL607W",
    carrier: "PIL (PACIFIC INTERNATIONAL LINES)",
    bookingNumber: "MGO-BK-2026-008",
    waybillNumber: "(H)PILFL26L12484VLP",
    containerNumber: "PILU4567890",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "DONGGUAN ACCESS TECH CO., LTD",
    shipperAddress:
      "DONGGUAN ACCESS TECH CO., LTD\nNO.92 DONGCHENG SOUTH RD, DONGCHENG DISTRICT\n523000, DONGGUAN, GUANGDONG, CHINA",
    customerReference: "ACCESS OC 8554",
    cargoDescription: "STC: GAMING ACCESSORIES & PERIPHERALS",
    typeOfMove: "FCL",
    totalCargo_Pieces: 60,
    totalCargo_WeightDisplayValue: "4,500.00 kg",
    totalCargo_VolumeDisplayValue: "32.000 m³",
    createdOn: "2026-01-01T08:25:00Z",
    hazardous: false,
    containerized: true,
    customsReleased: false,
    freightReleased: false,
  },

  // ── Operación 11: En tránsito (LCL) ──
  {
    id: 80011,
    number: "HBLI0008011",
    operationFlow: "Import",
    shipmentType: "Ocean",
    currentFlow: "In Transit",
    departure: "2026-02-12T04:00:00Z",
    arrival: "2026-03-28T04:00:00Z",
    portOfLoading: "PUERTO DE SHANGHAI",
    portOfUnloading: "SAN ANTONIO",
    placeOfDelivery: "Santiago, Chile",
    vessel: "YM WARRANTY",
    voyage: "FL608W",
    carrier: "YANG MING MARINE TRANSPORT",
    bookingNumber: "MGO-BK-2026-009",
    waybillNumber: "(H)YMFL26A05215SAI",
    containerNumber: "YMLU6789012",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "SHENZHEN GRAPHICS CARD CO., LTD",
    shipperAddress:
      "SHENZHEN GRAPHICS CARD CO., LTD\nBLOCK F, 8/F, NO.23 KEYUAN RD, NANSHAN DISTRICT\n518000, SHENZHEN, GUANGDONG, CHINA",
    customerReference: "GRAPHICS OC 20505",
    cargoDescription: "STC: HIGH-END GRAPHICS CARDS",
    typeOfMove: "LCL",
    totalCargo_Pieces: 10,
    totalCargo_WeightDisplayValue: "800.00 kg",
    totalCargo_VolumeDisplayValue: "3.500 m³",
    createdOn: "2026-02-07T17:35:00Z",
    hazardous: false,
    containerized: true,
    customsReleased: false,
    freightReleased: false,
  },

  // ── Operación 12: Ya arribó (FCL) ──
  {
    id: 80012,
    number: "HBLI0008012",
    operationFlow: "Import",
    shipmentType: "Ocean",
    currentFlow: "Arrived",
    departure: "2026-01-08T04:00:00Z",
    arrival: "2026-02-18T04:00:00Z",
    portOfLoading: "PUERTO DE QINGDAO",
    portOfUnloading: "VALPARAISO",
    placeOfDelivery: "Santiago, Chile",
    vessel: "OOCL ROTTERDAM",
    voyage: "FL609W",
    carrier: "ORIENT OVERSEAS CONTAINER LINE",
    bookingNumber: "MGO-BK-2026-010",
    waybillNumber: "(H)OOCLFL26L12485VLP",
    containerNumber: "OOLU8901234",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "DONGGUAN STORAGE SOLUTIONS CO., LTD",
    shipperAddress:
      "DONGGUAN STORAGE SOLUTIONS CO., LTD\nNO.93 DONGCHENG SOUTH RD, DONGCHENG DISTRICT\n523000, DONGGUAN, GUANGDONG, CHINA",
    customerReference: "STORAGE OC 8555",
    cargoDescription: "STC: HIGH-SPEED SSD DRIVES",
    typeOfMove: "FCL",
    totalCargo_Pieces: 35,
    totalCargo_WeightDisplayValue: "2,100.00 kg",
    totalCargo_VolumeDisplayValue: "15.800 m³",
    createdOn: "2026-01-03T12:55:00Z",
    hazardous: false,
    containerized: true,
    customsReleased: false,
    freightReleased: false,
  },
];
