/**
 * Datos dummy de ground-shipments exclusivos para la cuenta MundoGaming.
 * Estas operaciones son ficticias y no afectan KPIs ni datos reales de Linbis.
 */

import type { GroundShipment } from "./HandlerGroundShipments";

export const MUNDOGAMING_DUMMY_GROUND_SHIPMENTS: GroundShipment[] = [
  // ── Operación 1: En tránsito (FTL – carga completa) ──
  {
    id: 90001,
    number: "HBLI-GND-0001",
    operationFlow: "Import",
    shipmentType: "Ground",
    shipmentClass: "FTL",
    currentFlow: "In Transit",
    departure: "2026-02-10T08:00:00Z",
    arrival: "2026-02-12T18:00:00Z",
    from: "Valparaíso",
    to: "Santiago",
    finalDestination: "Bodega Central, Lampa",
    carrier: "TRANSPORTES CRUZ DEL SUR LTDA.",
    truckNumber: "FLXP-87",
    trackingNumber: "TRK-GND-2026-001",
    proNumber: "PRO-001-2026",
    driver: "Carlos Muñoz",
    bookingNumber: "MGT-BK-2026-001",
    waybillNumber: "GND-WB-26A0001",
    containerNumber: "",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "AGENTE ADUANAS VALPARAÍSO",
    shipperAddress:
      "AV. ERRÁZURIZ 930, PISO 5\nVALPARAÍSO, CHILE",
    customerReference: "OC-GAMING-20500",
    cargoDescription: "GAMING CONSOLES & ACCESSORIES (ex-marítimo)",
    rateCategory: "General Cargo",
    totalCargo_Pieces: 24,
    totalCargo_WeightDisplayValue: "3,200.00 kg",
    totalCargo_VolumeDisplayValue: "14.500 m³",
    createdOn: "2026-02-08T10:00:00Z",
    hazardous: false,
    customsReleased: true,
    freightReleased: true,
    paymentType: "Prepaid",
    declaredValue: 42500,
    pallets: 6,
    notes: "Retiro en puerto Valparaíso post desconsolidación marítima.",
  },

  // ── Operación 2: Entregada (LTL – carga parcial) ──
  {
    id: 90002,
    number: "HBLI-GND-0002",
    operationFlow: "Domestic",
    shipmentType: "Ground",
    shipmentClass: "LTL",
    currentFlow: "Delivered",
    departure: "2026-01-15T06:30:00Z",
    arrival: "2026-01-15T14:00:00Z",
    from: "Santiago",
    to: "Rancagua",
    finalDestination: "MundoGaming Sucursal Rancagua",
    carrier: "TURBUS CARGO S.A.",
    truckNumber: "JKRT-22",
    trackingNumber: "TRK-GND-2026-002",
    proNumber: "PRO-002-2026",
    driver: "José Tapia",
    bookingNumber: "MGT-BK-2026-002",
    waybillNumber: "GND-WB-26A0002",
    containerNumber: "",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "MUNDOGAMING SPA – Bodega Central",
    shipperAddress:
      "MUNDOGAMING SPA\nPARQUE INDUSTRIAL LAMPA, GALPÓN 14\nLAMPA, REGIÓN METROPOLITANA, CHILE",
    customerReference: "DIST-RCG-001",
    cargoDescription: "GAMING MONITORS & LED PANELS",
    rateCategory: "General Cargo",
    totalCargo_Pieces: 10,
    totalCargo_WeightDisplayValue: "780.00 kg",
    totalCargo_VolumeDisplayValue: "3.200 m³",
    createdOn: "2026-01-12T09:00:00Z",
    hazardous: false,
    customsReleased: true,
    freightReleased: true,
    paymentType: "Collect",
    declaredValue: 18900,
    pallets: 2,
    notes: "Distribución interna – sucursal Rancagua.",
  },

  // ── Operación 3: En tránsito (FTL – ruta larga norte) ──
  {
    id: 90003,
    number: "HBLI-GND-0003",
    operationFlow: "Domestic",
    shipmentType: "Ground",
    shipmentClass: "FTL",
    currentFlow: "In Transit",
    departure: "2026-02-14T05:00:00Z",
    arrival: "2026-02-16T20:00:00Z",
    from: "Santiago",
    to: "Antofagasta",
    finalDestination: "MundoGaming Sucursal Antofagasta",
    carrier: "STARKEN S.A.",
    truckNumber: "BGKL-55",
    trackingNumber: "TRK-GND-2026-003",
    proNumber: "PRO-003-2026",
    driver: "Miguel Contreras",
    bookingNumber: "MGT-BK-2026-003",
    waybillNumber: "GND-WB-26A0003",
    containerNumber: "",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "MUNDOGAMING SPA – Bodega Central",
    shipperAddress:
      "MUNDOGAMING SPA\nPARQUE INDUSTRIAL LAMPA, GALPÓN 14\nLAMPA, REGIÓN METROPOLITANA, CHILE",
    customerReference: "DIST-ANT-003",
    cargoDescription: "VR HEADSETS, GAMING LAPTOPS, CONTROLLERS",
    rateCategory: "General Cargo",
    totalCargo_Pieces: 35,
    totalCargo_WeightDisplayValue: "2,100.00 kg",
    totalCargo_VolumeDisplayValue: "10.800 m³",
    createdOn: "2026-02-10T11:30:00Z",
    hazardous: false,
    customsReleased: true,
    freightReleased: true,
    paymentType: "Prepaid",
    declaredValue: 67000,
    pallets: 8,
    notes: "Ruta Santiago → Antofagasta por Ruta 5 Norte. Aprox 1,300 km.",
  },

  // ── Operación 4: Pendiente de retiro (Pickup pending) ──
  {
    id: 90004,
    number: "HBLI-GND-0004",
    operationFlow: "Import",
    shipmentType: "Ground",
    shipmentClass: "FTL",
    currentFlow: "Pickup Pending",
    departure: "",
    arrival: "",
    from: "San Antonio",
    to: "Maipú",
    finalDestination: "Bodega Maipú, MundoGaming",
    carrier: "TRANSPORTES ANDES EXPRESS S.A.",
    truckNumber: "",
    trackingNumber: "TRK-GND-2026-004",
    proNumber: "PRO-004-2026",
    driver: "",
    bookingNumber: "MGT-BK-2026-004",
    waybillNumber: "GND-WB-26A0004",
    containerNumber: "MSCU9012345",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "AGENTE ADUANAS SAN ANTONIO",
    shipperAddress:
      "AV. BARROS LUCO 1540\nSAN ANTONIO, CHILE",
    customerReference: "OC-GAMING-20502-RET",
    cargoDescription: "GAMING CHAIRS & ERGONOMIC DESKS (ex-marítimo FCL)",
    rateCategory: "General Cargo",
    totalCargo_Pieces: 45,
    totalCargo_WeightDisplayValue: "4,320.00 kg",
    totalCargo_VolumeDisplayValue: "28.500 m³",
    createdOn: "2026-02-12T14:00:00Z",
    hazardous: false,
    customsReleased: false,
    freightReleased: false,
    paymentType: "Prepaid",
    declaredValue: 31000,
    pallets: 12,
    notes:
      "Contenedor aún en puerto San Antonio. Pendiente liberación aduanera.",
  },

  // ── Operación 5: Entregada (LTL – distribución Concepción) ──
  {
    id: 90005,
    number: "HBLI-GND-0005",
    operationFlow: "Domestic",
    shipmentType: "Ground",
    shipmentClass: "LTL",
    currentFlow: "Delivered",
    departure: "2026-01-20T07:00:00Z",
    arrival: "2026-01-21T10:30:00Z",
    from: "Santiago",
    to: "Concepción",
    finalDestination: "MundoGaming Sucursal Concepción",
    carrier: "CHILEXPRESS S.A.",
    truckNumber: "CHEX-99",
    trackingNumber: "TRK-GND-2026-005",
    proNumber: "PRO-005-2026",
    driver: "Roberto Fuentes",
    bookingNumber: "MGT-BK-2026-005",
    waybillNumber: "GND-WB-26A0005",
    containerNumber: "",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "MUNDOGAMING SPA – Bodega Central",
    shipperAddress:
      "MUNDOGAMING SPA\nPARQUE INDUSTRIAL LAMPA, GALPÓN 14\nLAMPA, REGIÓN METROPOLITANA, CHILE",
    customerReference: "DIST-CCP-005",
    cargoDescription: "STREAMING EQUIPMENT & PERIPHERALS",
    rateCategory: "General Cargo",
    totalCargo_Pieces: 18,
    totalCargo_WeightDisplayValue: "620.00 kg",
    totalCargo_VolumeDisplayValue: "2.900 m³",
    createdOn: "2026-01-18T08:45:00Z",
    hazardous: false,
    customsReleased: true,
    freightReleased: true,
    paymentType: "Prepaid",
    declaredValue: 22500,
    pallets: 3,
    notes: "Distribución zona sur – Sucursal Concepción.",
  },

  // ── Operación 6: En tránsito (FTL – carga peligrosa) ──
  {
    id: 90006,
    number: "HBLI-GND-0006",
    operationFlow: "Domestic",
    shipmentType: "Ground",
    shipmentClass: "FTL",
    currentFlow: "In Transit",
    departure: "2026-02-18T04:00:00Z",
    arrival: "2026-02-18T16:00:00Z",
    from: "Lampa",
    to: "Valparaíso",
    finalDestination: "Puerto Valparaíso – Zona Export",
    carrier: "TRANSPORTES HAZMAT CHILE LTDA.",
    truckNumber: "HZMT-13",
    trackingNumber: "TRK-GND-2026-006",
    proNumber: "PRO-006-2026",
    driver: "Andrés Vega",
    bookingNumber: "MGT-BK-2026-006",
    waybillNumber: "GND-WB-26A0006",
    containerNumber: "",
    consignee: "AGENTE EXPORTACIÓN VALPARAÍSO",
    consigneeId: 50001,
    consigneeAddress:
      "AGENCIA DE ADUANAS EXPORTA CHILE\nAV. ERRÁZURIZ 1100\nVALPARAÍSO, CHILE",
    shipper: "MundoGaming",
    shipperAddress:
      "MUNDOGAMING SPA\nPARQUE INDUSTRIAL LAMPA, GALPÓN 14\nLAMPA, REGIÓN METROPOLITANA, CHILE",
    customerReference: "EXP-BAT-006",
    cargoDescription: "LITHIUM BATTERIES FOR GAMING CONTROLLERS (HAZMAT)",
    rateCategory: "Hazardous",
    totalCargo_Pieces: 4,
    totalCargo_WeightDisplayValue: "320.00 kg",
    totalCargo_VolumeDisplayValue: "1.200 m³",
    createdOn: "2026-02-15T09:00:00Z",
    hazardous: true,
    customsReleased: false,
    freightReleased: false,
    paymentType: "Prepaid",
    declaredValue: 95000,
    pallets: 2,
    notes:
      "Transporte ADR – baterías de litio clase 9. Documentación MSDS requerida.",
  },

  // ── Operación 7: Entregada (LTL – Temuco) ──
  {
    id: 90007,
    number: "HBLI-GND-0007",
    operationFlow: "Domestic",
    shipmentType: "Ground",
    shipmentClass: "LTL",
    currentFlow: "Delivered",
    departure: "2026-01-25T06:00:00Z",
    arrival: "2026-01-26T15:00:00Z",
    from: "Santiago",
    to: "Temuco",
    finalDestination: "MundoGaming Sucursal Temuco",
    carrier: "PULLMAN CARGO S.A.",
    truckNumber: "PULL-44",
    trackingNumber: "TRK-GND-2026-007",
    proNumber: "PRO-007-2026",
    driver: "Patricio Soto",
    bookingNumber: "MGT-BK-2026-007",
    waybillNumber: "GND-WB-26A0007",
    containerNumber: "",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "MUNDOGAMING SPA – Bodega Central",
    shipperAddress:
      "MUNDOGAMING SPA\nPARQUE INDUSTRIAL LAMPA, GALPÓN 14\nLAMPA, REGIÓN METROPOLITANA, CHILE",
    customerReference: "DIST-TMC-007",
    cargoDescription: "GAMING HEADSETS & AUDIO EQUIPMENT",
    rateCategory: "General Cargo",
    totalCargo_Pieces: 22,
    totalCargo_WeightDisplayValue: "450.00 kg",
    totalCargo_VolumeDisplayValue: "1.800 m³",
    createdOn: "2026-01-22T11:15:00Z",
    hazardous: false,
    customsReleased: true,
    freightReleased: true,
    paymentType: "Collect",
    declaredValue: 14200,
    pallets: 3,
    notes: "Distribución zona sur – Sucursal Temuco.",
  },

  // ── Operación 8: En tránsito (FTL – cross-docking) ──
  {
    id: 90008,
    number: "HBLI-GND-0008",
    operationFlow: "Import",
    shipmentType: "Ground",
    shipmentClass: "FTL",
    currentFlow: "In Transit",
    departure: "2026-02-20T03:00:00Z",
    arrival: "2026-02-20T11:00:00Z",
    from: "San Antonio",
    to: "Santiago",
    finalDestination: "Cross-dock Pudahuel, MundoGaming",
    carrier: "TRANSPORTES CRUZ DEL SUR LTDA.",
    truckNumber: "FLXP-91",
    trackingNumber: "TRK-GND-2026-008",
    proNumber: "PRO-008-2026",
    driver: "Hernán Lagos",
    bookingNumber: "MGT-BK-2026-008",
    waybillNumber: "GND-WB-26A0008",
    containerNumber: "CMAU3456789",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "AGENTE ADUANAS SAN ANTONIO",
    shipperAddress:
      "AV. BARROS LUCO 1540\nSAN ANTONIO, CHILE",
    customerReference: "OC-GAMING-20501-XDK",
    cargoDescription: "GAMING LAPTOPS & HIGH-END PCS (ex-marítimo LCL)",
    rateCategory: "General Cargo",
    totalCargo_Pieces: 8,
    totalCargo_WeightDisplayValue: "1,200.00 kg",
    totalCargo_VolumeDisplayValue: "6.500 m³",
    createdOn: "2026-02-18T16:00:00Z",
    hazardous: false,
    customsReleased: true,
    freightReleased: true,
    paymentType: "Prepaid",
    declaredValue: 55000,
    pallets: 4,
    notes: "Cross-docking en Pudahuel para redistribución nacional.",
  },

  // ── Operación 9: Entregada (LTL – Viña del Mar) ──
  {
    id: 90009,
    number: "HBLI-GND-0009",
    operationFlow: "Domestic",
    shipmentType: "Ground",
    shipmentClass: "LTL",
    currentFlow: "Delivered",
    departure: "2026-02-05T08:00:00Z",
    arrival: "2026-02-05T12:00:00Z",
    from: "Santiago",
    to: "Viña del Mar",
    finalDestination: "MundoGaming Sucursal Viña",
    carrier: "TURBUS CARGO S.A.",
    truckNumber: "JKRT-30",
    trackingNumber: "TRK-GND-2026-009",
    proNumber: "PRO-009-2026",
    driver: "Luis Araya",
    bookingNumber: "MGT-BK-2026-009",
    waybillNumber: "GND-WB-26A0009",
    containerNumber: "",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "MUNDOGAMING SPA – Bodega Central",
    shipperAddress:
      "MUNDOGAMING SPA\nPARQUE INDUSTRIAL LAMPA, GALPÓN 14\nLAMPA, REGIÓN METROPOLITANA, CHILE",
    customerReference: "DIST-VNA-009",
    cargoDescription: "GAMING KEYBOARDS & MICE – MECHANICAL PRO SERIES",
    rateCategory: "General Cargo",
    totalCargo_Pieces: 50,
    totalCargo_WeightDisplayValue: "380.00 kg",
    totalCargo_VolumeDisplayValue: "1.500 m³",
    createdOn: "2026-02-03T13:00:00Z",
    hazardous: false,
    customsReleased: true,
    freightReleased: true,
    paymentType: "Prepaid",
    declaredValue: 9800,
    pallets: 2,
    notes: "Distribución V Región – Sucursal Viña del Mar.",
  },

  // ── Operación 10: En tránsito (FTL – Iquique) ──
  {
    id: 90010,
    number: "HBLI-GND-0010",
    operationFlow: "Import",
    shipmentType: "Ground",
    shipmentClass: "FTL",
    currentFlow: "In Transit",
    departure: "2026-02-22T04:00:00Z",
    arrival: "2026-02-25T22:00:00Z",
    from: "Iquique",
    to: "Santiago",
    finalDestination: "Bodega Central, Lampa",
    carrier: "TRANSPORTES NORTE GRANDE S.A.",
    truckNumber: "NRTG-07",
    trackingNumber: "TRK-GND-2026-010",
    proNumber: "PRO-010-2026",
    driver: "Fernando Díaz",
    bookingNumber: "MGT-BK-2026-010",
    waybillNumber: "GND-WB-26A0010",
    containerNumber: "",
    consignee: "MundoGaming",
    consigneeId: 50001,
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    shipper: "ZONA FRANCA DE IQUIQUE – ZOFRI",
    shipperAddress:
      "RECINTO AMURALLADO, MÓDULO 8\nZONA FRANCA IQUIQUE\nIQUIQUE, TARAPACÁ, CHILE",
    customerReference: "ZOFRI-IMP-010",
    cargoDescription: "GAMING PERIPHERALS & ACCESSORIES (ZOFRI import)",
    rateCategory: "General Cargo",
    totalCargo_Pieces: 60,
    totalCargo_WeightDisplayValue: "5,400.00 kg",
    totalCargo_VolumeDisplayValue: "32.000 m³",
    createdOn: "2026-02-19T10:00:00Z",
    hazardous: false,
    customsReleased: true,
    freightReleased: true,
    paymentType: "Prepaid",
    declaredValue: 125000,
    pallets: 15,
    notes:
      "Ruta Iquique → Santiago por Ruta 5 Norte. Aprox 1,800 km. Carga ZOFRI.",
  },
];
