/**
 * Datos dummy exclusivos para la cuenta MundoGaming.
 * Estas operaciones son ficticias y no afectan KPIs ni datos reales de Linbis.
 */

import type { AirShipment } from "./Handlersairshipments";

export const MUNDOGAMING_DUMMY_SHIPMENTS: AirShipment[] = [
  // ── Operación 1: En tránsito (salida reciente, llegada futura) ──
  {
    id: 90001,
    number: "123-45678912",
    waybillNumber: "MGA26002100A",
    containerNumber: null,
    containerSealNumberOne: null,
    carrier: {
      id: 31200,
      name: "LATAM CARGO",
      accountNumber: null,
      code: "1075",
      email: null,
    },
    consignee: {
      id: 50001,
      name: "MUNDOGAMING SPA",
      accountNumber: "77.123.456-7",
      code: "MG01",
      email: "contacto@mundogaming.cl",
    },
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    customerReference: "SHENZHEN TECHZONE OC 10250",
    cargoDescription: "F.A.K. - Freight All Kinds",
    headload: false,
    hazardous: false,
    departure: {
      type: "SplitDateTime",
      date: "2026-02-08T04:00:00Z",
      time: null,
      displayDate: "02/08/2026",
      displayTime: "",
    },
    arrival: {
      type: "SplitDateTime",
      date: "2026-02-18T04:00:00Z",
      time: null,
      displayDate: "02/18/2026",
      displayTime: "",
    },
    loadingDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    executedOn: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    releaseDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    shipper: {
      id: 60001,
      name: "SHENZHEN TECHZONE ELECTRONICS CO., LTD",
      accountNumber: null,
      code: "TECHZONE-5120",
    },
    shipperAddress:
      "SHENZHEN TECHZONE ELECTRONICS CO., LTD\nBLOCK A, 3/F, NO.18 KEYUAN RD, NANSHAN DISTRICT\n518000, SHENZHEN, GUANGDONG, CHINA",
    notifyPartyAddress: "SAME AS CNEE\n  \n  \n",
    forwardingAgentAddress:
      "BLUE CARGO LOGISTICS CO.,LTD.\n37TH FLOOR, NO.6 SHANDONG ROAD, SHINAN DISTRICT, Q  \n  CHINA\n \n",
    destinationAgentAddress:
      "SEEMANN Y CIA LTDA\nAV. PROVIDENCIA 1650, PROVIDENCIA  \nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:76.583.910-6",
    fowaredBl: "MGA26002100A",
    manifestedPieces: 0,
    manifestedWeight: 0.0,
    paymentType: 1,
    shipmentClass: 1,
    operationFlow: 1,
    shipmentType: 2,
    parentShipmentId: null,
    commodities: [
      {
        commodityType: 1,
        pieces: 5,
        description: "STC\nGAMING PERIPHERALS\nKEYBOARDS, MICE, HEADSETS",
        totalWeightValue: 120.0,
        totalWeightUOM: 2,
        totalVolumeValue: 0.85,
        totalVolumeUOM: 2,
        packageType: {
          id: 97,
          description: "BOX",
          isShippingContainer: false,
        },
        id: 70001,
      },
    ],
    subShipments: [
      {
        id: 91001,
        number: "MGA26002100A-H1",
        waybillNumber: "MGA26002100A",
        consignee: {
          id: 50001,
          name: "MUNDOGAMING SPA",
        },
        consigneeAddress:
          "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nSANTIAGO CHILE",
        carrier: { id: 31200, name: "LATAM CARGO" },
        cargoDescription: "F.A.K. - Freight All Kinds",
        manifestedPieces: 5,
        manifestedWeight: 120.0,
        customerReference: "SHENZHEN TECHZONE OC 10250",
        commodities: [
          {
            pieces: 3,
            description: "GAMING KEYBOARDS MECHANICAL RGB",
            totalWeightValue: 45.0,
            totalVolumeValue: 0.35,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
          {
            pieces: 2,
            description: "GAMING HEADSETS 7.1 SURROUND",
            totalWeightValue: 75.0,
            totalVolumeValue: 0.5,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
        ],
      },
    ],
    notes: null,
  },

  // ── Operación 2: Ya llegó (fecha de llegada pasada) ──
  {
    id: 90002,
    number: "231-12345678",
    waybillNumber: "MGA26001850B",
    containerNumber: null,
    containerSealNumberOne: null,
    carrier: {
      id: 27818,
      name: "DELTA AIR LINES",
      accountNumber: null,
      code: "6975",
      email: null,
    },
    consignee: {
      id: 50001,
      name: "MUNDOGAMING SPA",
      accountNumber: "77.123.456-7",
      code: "MG01",
      email: "contacto@mundogaming.cl",
    },
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    customerReference: "DONGGUAN PIXELGEAR OC 8420 / SHENZHEN TECHZONE OC 10180",
    cargoDescription: "F.A.K. - Freight All Kinds",
    headload: false,
    hazardous: false,
    departure: {
      type: "SplitDateTime",
      date: "2026-01-20T04:00:00Z",
      time: null,
      displayDate: "01/20/2026",
      displayTime: "",
    },
    arrival: {
      type: "SplitDateTime",
      date: "2026-01-28T04:00:00Z",
      time: null,
      displayDate: "01/28/2026",
      displayTime: "",
    },
    loadingDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    executedOn: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    releaseDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    shipper: {
      id: 60002,
      name: "DONGGUAN PIXELGEAR TECHNOLOGY CO., LTD",
      accountNumber: null,
      code: "PIXELGEAR-3300",
    },
    shipperAddress:
      "DONGGUAN PIXELGEAR TECHNOLOGY CO., LTD\nNO.88 DONGCHENG SOUTH RD, DONGCHENG DISTRICT\n523000, DONGGUAN, GUANGDONG, CHINA",
    notifyPartyAddress: "SAME AS CNEE\n  \n  \n",
    forwardingAgentAddress:
      "BLUE CARGO LOGISTICS CO.,LTD.\n37TH FLOOR, NO.6 SHANDONG ROAD, SHINAN DISTRICT, Q  \n  CHINA\n \n",
    destinationAgentAddress:
      "SEEMANN Y CIA LTDA\nAV. PROVIDENCIA 1650, PROVIDENCIA  \nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:76.583.910-6",
    fowaredBl: "MGA26001850B",
    manifestedPieces: 0,
    manifestedWeight: 0.0,
    paymentType: 1,
    shipmentClass: 1,
    operationFlow: 1,
    shipmentType: 2,
    parentShipmentId: null,
    commodities: [
      {
        commodityType: 1,
        pieces: 8,
        description: "STC\nGAMING MONITORS\nLED MONITORS 27 INCH 144HZ",
        totalWeightValue: 210.0,
        totalWeightUOM: 2,
        totalVolumeValue: 2.4,
        totalVolumeUOM: 2,
        packageType: {
          id: 97,
          description: "BOX",
          isShippingContainer: false,
        },
        id: 70002,
      },
    ],
    subShipments: [
      {
        id: 91002,
        number: "MGA26001850B-H1",
        waybillNumber: "MGA26001850B",
        consignee: {
          id: 50001,
          name: "MUNDOGAMING SPA",
        },
        consigneeAddress:
          "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nSANTIAGO CHILE",
        carrier: { id: 27818, name: "DELTA AIR LINES" },
        cargoDescription: "F.A.K. - Freight All Kinds",
        manifestedPieces: 8,
        manifestedWeight: 210.0,
        customerReference: "DONGGUAN PIXELGEAR OC 8420 / SHENZHEN TECHZONE OC 10180",
        commodities: [
          {
            pieces: 5,
            description: "GAMING MONITORS LED 27\" 144HZ IPS",
            totalWeightValue: 150.0,
            totalVolumeValue: 1.8,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
          {
            pieces: 3,
            description: "GAMING CONTROLLERS WIRELESS PRO",
            totalWeightValue: 60.0,
            totalVolumeValue: 0.6,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
        ],
      },
    ],
    notes: null,
  },

  // ── Operación 3: En tránsito ──
  {
    id: 90003,
    number: "124-45678913",
    waybillNumber: "MGA26002101A",
    containerNumber: null,
    containerSealNumberOne: null,
    carrier: {
      id: 27819,
      name: "AMERICAN AIRLINES",
      accountNumber: null,
      code: "001",
      email: null,
    },
    consignee: {
      id: 50001,
      name: "MUNDOGAMING SPA",
      accountNumber: "77.123.456-7",
      code: "MG01",
      email: "contacto@mundogaming.cl",
    },
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    customerReference: "SHENZHEN GAMING OC 10251",
    cargoDescription: "F.A.K. - Freight All Kinds",
    headload: false,
    hazardous: false,
    departure: {
      type: "SplitDateTime",
      date: "2026-02-10T04:00:00Z",
      time: null,
      displayDate: "02/10/2026",
      displayTime: "",
    },
    arrival: {
      type: "SplitDateTime",
      date: "2026-02-20T04:00:00Z",
      time: null,
      displayDate: "02/20/2026",
      displayTime: "",
    },
    loadingDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    executedOn: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    releaseDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    shipper: {
      id: 60003,
      name: "SHENZHEN GAMING ELECTRONICS CO., LTD",
      accountNumber: null,
      code: "GAMING-5121",
    },
    shipperAddress:
      "SHENZHEN GAMING ELECTRONICS CO., LTD\nBLOCK B, 4/F, NO.19 KEYUAN RD, NANSHAN DISTRICT\n518000, SHENZHEN, GUANGDONG, CHINA",
    notifyPartyAddress: "SAME AS CNEE\n  \n  \n",
    forwardingAgentAddress:
      "BLUE CARGO LOGISTICS CO.,LTD.\n37TH FLOOR, NO.6 SHANDONG ROAD, SHINAN DISTRICT, Q  \n  CHINA\n \n",
    destinationAgentAddress:
      "SEEMANN Y CIA LTDA\nAV. PROVIDENCIA 1650, PROVIDENCIA  \nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:76.583.910-6",
    fowaredBl: "MGA26002101A",
    manifestedPieces: 0,
    manifestedWeight: 0.0,
    paymentType: 1,
    shipmentClass: 1,
    operationFlow: 1,
    shipmentType: 2,
    parentShipmentId: null,
    commodities: [
      {
        commodityType: 1,
        pieces: 6,
        description: "STC\nGAMING LAPTOPS\nHIGH-PERFORMANCE GAMING LAPTOPS",
        totalWeightValue: 150.0,
        totalWeightUOM: 2,
        totalVolumeValue: 1.2,
        totalVolumeUOM: 2,
        packageType: {
          id: 97,
          description: "BOX",
          isShippingContainer: false,
        },
        id: 70003,
      },
    ],
    subShipments: [
      {
        id: 91003,
        number: "MGA26002101A-H1",
        waybillNumber: "MGA26002101A",
        consignee: {
          id: 50001,
          name: "MUNDOGAMING SPA",
        },
        consigneeAddress:
          "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nSANTIAGO CHILE",
        carrier: { id: 27819, name: "AMERICAN AIRLINES" },
        cargoDescription: "F.A.K. - Freight All Kinds",
        manifestedPieces: 6,
        manifestedWeight: 150.0,
        customerReference: "SHENZHEN GAMING OC 10251",
        commodities: [
          {
            pieces: 4,
            description: "GAMING LAPTOPS 15.6\" RTX 4070",
            totalWeightValue: 100.0,
            totalVolumeValue: 0.8,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
          {
            pieces: 2,
            description: "GAMING MOUSE PADS RGB",
            totalWeightValue: 50.0,
            totalVolumeValue: 0.4,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
        ],
      },
    ],
    notes: null,
  },

  // ── Operación 4: Ya llegó ──
  {
    id: 90004,
    number: "125-45678914",
    waybillNumber: "MGA26001851B",
    containerNumber: null,
    containerSealNumberOne: null,
    carrier: {
      id: 27820,
      name: "UNITED AIRLINES",
      accountNumber: null,
      code: "016",
      email: null,
    },
    consignee: {
      id: 50001,
      name: "MUNDOGAMING SPA",
      accountNumber: "77.123.456-7",
      code: "MG01",
      email: "contacto@mundogaming.cl",
    },
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    customerReference: "DONGGUAN PROGAMING OC 8421",
    cargoDescription: "F.A.K. - Freight All Kinds",
    headload: false,
    hazardous: false,
    departure: {
      type: "SplitDateTime",
      date: "2026-01-15T04:00:00Z",
      time: null,
      displayDate: "01/15/2026",
      displayTime: "",
    },
    arrival: {
      type: "SplitDateTime",
      date: "2026-01-25T04:00:00Z",
      time: null,
      displayDate: "01/25/2026",
      displayTime: "",
    },
    loadingDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    executedOn: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    releaseDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    shipper: {
      id: 60004,
      name: "DONGGUAN PROGAMING TECH CO., LTD",
      accountNumber: null,
      code: "PROGAMING-3301",
    },
    shipperAddress:
      "DONGGUAN PROGAMING TECH CO., LTD\nNO.89 DONGCHENG SOUTH RD, DONGCHENG DISTRICT\n523000, DONGGUAN, GUANGDONG, CHINA",
    notifyPartyAddress: "SAME AS CNEE\n  \n  \n",
    forwardingAgentAddress:
      "BLUE CARGO LOGISTICS CO.,LTD.\n37TH FLOOR, NO.6 SHANDONG ROAD, SHINAN DISTRICT, Q  \n  CHINA\n \n",
    destinationAgentAddress:
      "SEEMANN Y CIA LTDA\nAV. PROVIDENCIA 1650, PROVIDENCIA  \nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:76.583.910-6",
    fowaredBl: "MGA26001851B",
    manifestedPieces: 0,
    manifestedWeight: 0.0,
    paymentType: 1,
    shipmentClass: 1,
    operationFlow: 1,
    shipmentType: 2,
    parentShipmentId: null,
    commodities: [
      {
        commodityType: 1,
        pieces: 10,
        description: "STC\nGAMING CHAIRS\nERGONOMIC GAMING CHAIRS",
        totalWeightValue: 250.0,
        totalWeightUOM: 2,
        totalVolumeValue: 3.0,
        totalVolumeUOM: 2,
        packageType: {
          id: 97,
          description: "BOX",
          isShippingContainer: false,
        },
        id: 70004,
      },
    ],
    subShipments: [
      {
        id: 91004,
        number: "MGA26001851B-H1",
        waybillNumber: "MGA26001851B",
        consignee: {
          id: 50001,
          name: "MUNDOGAMING SPA",
        },
        consigneeAddress:
          "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nSANTIAGO CHILE",
        carrier: { id: 27820, name: "UNITED AIRLINES" },
        cargoDescription: "F.A.K. - Freight All Kinds",
        manifestedPieces: 10,
        manifestedWeight: 250.0,
        customerReference: "DONGGUAN PROGAMING OC 8421",
        commodities: [
          {
            pieces: 7,
            description: "GAMING CHAIRS ERGONOMIC BLACK",
            totalWeightValue: 175.0,
            totalVolumeValue: 2.1,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
          {
            pieces: 3,
            description: "GAMING DESKS ADJUSTABLE",
            totalWeightValue: 75.0,
            totalVolumeValue: 0.9,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
        ],
      },
    ],
    notes: null,
  },

  // ── Operación 5: En tránsito ──
  {
    id: 90005,
    number: "126-45678915",
    waybillNumber: "MGA26002102A",
    containerNumber: null,
    containerSealNumberOne: null,
    carrier: {
      id: 27821,
      name: "LUFTHANSA CARGO",
      accountNumber: null,
      code: "020",
      email: null,
    },
    consignee: {
      id: 50001,
      name: "MUNDOGAMING SPA",
      accountNumber: "77.123.456-7",
      code: "MG01",
      email: "contacto@mundogaming.cl",
    },
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    customerReference: "SHENZHEN VRZONE OC 10252",
    cargoDescription: "F.A.K. - Freight All Kinds",
    headload: false,
    hazardous: false,
    departure: {
      type: "SplitDateTime",
      date: "2026-02-12T04:00:00Z",
      time: null,
      displayDate: "02/12/2026",
      displayTime: "",
    },
    arrival: {
      type: "SplitDateTime",
      date: "2026-02-22T04:00:00Z",
      time: null,
      displayDate: "02/22/2026",
      displayTime: "",
    },
    loadingDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    executedOn: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    releaseDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    shipper: {
      id: 60005,
      name: "SHENZHEN VRZONE ELECTRONICS CO., LTD",
      accountNumber: null,
      code: "VRZONE-5122",
    },
    shipperAddress:
      "SHENZHEN VRZONE ELECTRONICS CO., LTD\nBLOCK C, 5/F, NO.20 KEYUAN RD, NANSHAN DISTRICT\n518000, SHENZHEN, GUANGDONG, CHINA",
    notifyPartyAddress: "SAME AS CNEE\n  \n  \n",
    forwardingAgentAddress:
      "BLUE CARGO LOGISTICS CO.,LTD.\n37TH FLOOR, NO.6 SHANDONG ROAD, SHINAN DISTRICT, Q  \n  CHINA\n \n",
    destinationAgentAddress:
      "SEEMANN Y CIA LTDA\nAV. PROVIDENCIA 1650, PROVIDENCIA  \nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:76.583.910-6",
    fowaredBl: "MGA26002102A",
    manifestedPieces: 0,
    manifestedWeight: 0.0,
    paymentType: 1,
    shipmentClass: 1,
    operationFlow: 1,
    shipmentType: 2,
    parentShipmentId: null,
    commodities: [
      {
        commodityType: 1,
        pieces: 4,
        description: "STC\nVR HEADSETS\nVIRTUAL REALITY HEADSETS",
        totalWeightValue: 80.0,
        totalWeightUOM: 2,
        totalVolumeValue: 0.6,
        totalVolumeUOM: 2,
        packageType: {
          id: 97,
          description: "BOX",
          isShippingContainer: false,
        },
        id: 70005,
      },
    ],
    subShipments: [
      {
        id: 91005,
        number: "MGA26002102A-H1",
        waybillNumber: "MGA26002102A",
        consignee: {
          id: 50001,
          name: "MUNDOGAMING SPA",
        },
        consigneeAddress:
          "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nSANTIAGO CHILE",
        carrier: { id: 27821, name: "LUFTHANSA CARGO" },
        cargoDescription: "F.A.K. - Freight All Kinds",
        manifestedPieces: 4,
        manifestedWeight: 80.0,
        customerReference: "SHENZHEN VRZONE OC 10252",
        commodities: [
          {
            pieces: 4,
            description: "VR HEADSETS WIRELESS 4K",
            totalWeightValue: 80.0,
            totalVolumeValue: 0.6,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
        ],
      },
    ],
    notes: null,
  },

  // ── Operación 6: Ya llegó ──
  {
    id: 90006,
    number: "127-45678916",
    waybillNumber: "MGA26001852B",
    containerNumber: null,
    containerSealNumberOne: null,
    carrier: {
      id: 27822,
      name: "AIR FRANCE CARGO",
      accountNumber: null,
      code: "057",
      email: null,
    },
    consignee: {
      id: 50001,
      name: "MUNDOGAMING SPA",
      accountNumber: "77.123.456-7",
      code: "MG01",
      email: "contacto@mundogaming.cl",
    },
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    customerReference: "DONGGUAN STREAMTECH OC 8422",
    cargoDescription: "F.A.K. - Freight All Kinds",
    headload: false,
    hazardous: false,
    departure: {
      type: "SplitDateTime",
      date: "2026-01-18T04:00:00Z",
      time: null,
      displayDate: "01/18/2026",
      displayTime: "",
    },
    arrival: {
      type: "SplitDateTime",
      date: "2026-01-28T04:00:00Z",
      time: null,
      displayDate: "01/28/2026",
      displayTime: "",
    },
    loadingDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    executedOn: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    releaseDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    shipper: {
      id: 60006,
      name: "DONGGUAN STREAMTECH CO., LTD",
      accountNumber: null,
      code: "STREAMTECH-3302",
    },
    shipperAddress:
      "DONGGUAN STREAMTECH CO., LTD\nNO.90 DONGCHENG SOUTH RD, DONGCHENG DISTRICT\n523000, DONGGUAN, GUANGDONG, CHINA",
    notifyPartyAddress: "SAME AS CNEE\n  \n  \n",
    forwardingAgentAddress:
      "BLUE CARGO LOGISTICS CO.,LTD.\n37TH FLOOR, NO.6 SHANDONG ROAD, SHINAN DISTRICT, Q  \n  CHINA\n \n",
    destinationAgentAddress:
      "SEEMANN Y CIA LTDA\nAV. PROVIDENCIA 1650, PROVIDENCIA  \nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:76.583.910-6",
    fowaredBl: "MGA26001852B",
    manifestedPieces: 0,
    manifestedWeight: 0.0,
    paymentType: 1,
    shipmentClass: 1,
    operationFlow: 1,
    shipmentType: 2,
    parentShipmentId: null,
    commodities: [
      {
        commodityType: 1,
        pieces: 12,
        description: "STC\nSTREAMING EQUIPMENT\nWEBCAMS AND MICROPHONES",
        totalWeightValue: 180.0,
        totalWeightUOM: 2,
        totalVolumeValue: 1.8,
        totalVolumeUOM: 2,
        packageType: {
          id: 97,
          description: "BOX",
          isShippingContainer: false,
        },
        id: 70006,
      },
    ],
    subShipments: [
      {
        id: 91006,
        number: "MGA26001852B-H1",
        waybillNumber: "MGA26001852B",
        consignee: {
          id: 50001,
          name: "MUNDOGAMING SPA",
        },
        consigneeAddress:
          "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nSANTIAGO CHILE",
        carrier: { id: 27822, name: "AIR FRANCE CARGO" },
        cargoDescription: "F.A.K. - Freight All Kinds",
        manifestedPieces: 12,
        manifestedWeight: 180.0,
        customerReference: "DONGGUAN STREAMTECH OC 8422",
        commodities: [
          {
            pieces: 8,
            description: "WEBCAMS 4K STREAMING",
            totalWeightValue: 120.0,
            totalVolumeValue: 1.2,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
          {
            pieces: 4,
            description: "CONDENSER MICROPHONES",
            totalWeightValue: 60.0,
            totalVolumeValue: 0.6,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
        ],
      },
    ],
    notes: null,
  },

  // ── Operación 7: En tránsito ──
  {
    id: 90007,
    number: "128-45678917",
    waybillNumber: "MGA26002103A",
    containerNumber: null,
    containerSealNumberOne: null,
    carrier: {
      id: 27823,
      name: "CATHAY PACIFIC CARGO",
      accountNumber: null,
      code: "160",
      email: null,
    },
    consignee: {
      id: 50001,
      name: "MUNDOGAMING SPA",
      accountNumber: "77.123.456-7",
      code: "MG01",
      email: "contacto@mundogaming.cl",
    },
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    customerReference: "SHENZHEN CONSOLE OC 10253",
    cargoDescription: "F.A.K. - Freight All Kinds",
    headload: false,
    hazardous: false,
    departure: {
      type: "SplitDateTime",
      date: "2026-02-14T04:00:00Z",
      time: null,
      displayDate: "02/14/2026",
      displayTime: "",
    },
    arrival: {
      type: "SplitDateTime",
      date: "2026-02-24T04:00:00Z",
      time: null,
      displayDate: "02/24/2026",
      displayTime: "",
    },
    loadingDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    executedOn: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    releaseDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    shipper: {
      id: 60007,
      name: "SHENZHEN CONSOLE TECH CO., LTD",
      accountNumber: null,
      code: "CONSOLE-5123",
    },
    shipperAddress:
      "SHENZHEN CONSOLE TECH CO., LTD\nBLOCK D, 6/F, NO.21 KEYUAN RD, NANSHAN DISTRICT\n518000, SHENZHEN, GUANGDONG, CHINA",
    notifyPartyAddress: "SAME AS CNEE\n  \n  \n",
    forwardingAgentAddress:
      "BLUE CARGO LOGISTICS CO.,LTD.\n37TH FLOOR, NO.6 SHANDONG ROAD, SHINAN DISTRICT, Q  \n  CHINA\n \n",
    destinationAgentAddress:
      "SEEMANN Y CIA LTDA\nAV. PROVIDENCIA 1650, PROVIDENCIA  \nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:76.583.910-6",
    fowaredBl: "MGA26002103A",
    manifestedPieces: 0,
    manifestedWeight: 0.0,
    paymentType: 1,
    shipmentClass: 1,
    operationFlow: 1,
    shipmentType: 2,
    parentShipmentId: null,
    commodities: [
      {
        commodityType: 1,
        pieces: 7,
        description: "STC\nGAMING CONSOLES\nNEXT-GEN GAMING CONSOLES",
        totalWeightValue: 140.0,
        totalWeightUOM: 2,
        totalVolumeValue: 1.0,
        totalVolumeUOM: 2,
        packageType: {
          id: 97,
          description: "BOX",
          isShippingContainer: false,
        },
        id: 70007,
      },
    ],
    subShipments: [
      {
        id: 91007,
        number: "MGA26002103A-H1",
        waybillNumber: "MGA26002103A",
        consignee: {
          id: 50001,
          name: "MUNDOGAMING SPA",
        },
        consigneeAddress:
          "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nSANTIAGO CHILE",
        carrier: { id: 27823, name: "CATHAY PACIFIC CARGO" },
        cargoDescription: "F.A.K. - Freight All Kinds",
        manifestedPieces: 7,
        manifestedWeight: 140.0,
        customerReference: "SHENZHEN CONSOLE OC 10253",
        commodities: [
          {
            pieces: 5,
            description: "GAMING CONSOLES PS6",
            totalWeightValue: 100.0,
            totalVolumeValue: 0.7,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
          {
            pieces: 2,
            description: "GAMING ACCESSORIES BUNDLES",
            totalWeightValue: 40.0,
            totalVolumeValue: 0.3,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
        ],
      },
    ],
    notes: null,
  },

  // ── Operación 8: Ya llegó ──
  {
    id: 90008,
    number: "129-45678918",
    waybillNumber: "MGA26001853B",
    containerNumber: null,
    containerSealNumberOne: null,
    carrier: {
      id: 27824,
      name: "QANTAS AIRWAYS",
      accountNumber: null,
      code: "081",
      email: null,
    },
    consignee: {
      id: 50001,
      name: "MUNDOGAMING SPA",
      accountNumber: "77.123.456-7",
      code: "MG01",
      email: "contacto@mundogaming.cl",
    },
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    customerReference: "DONGGUAN LIGHTING OC 8423",
    cargoDescription: "F.A.K. - Freight All Kinds",
    headload: false,
    hazardous: false,
    departure: {
      type: "SplitDateTime",
      date: "2026-01-22T04:00:00Z",
      time: null,
      displayDate: "01/22/2026",
      displayTime: "",
    },
    arrival: {
      type: "SplitDateTime",
      date: "2026-02-01T04:00:00Z",
      time: null,
      displayDate: "02/01/2026",
      displayTime: "",
    },
    loadingDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    executedOn: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    releaseDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    shipper: {
      id: 60008,
      name: "DONGGUAN LIGHTING PRO CO., LTD",
      accountNumber: null,
      code: "LIGHTING-3303",
    },
    shipperAddress:
      "DONGGUAN LIGHTING PRO CO., LTD\nNO.91 DONGCHENG SOUTH RD, DONGCHENG DISTRICT\n523000, DONGGUAN, GUANGDONG, CHINA",
    notifyPartyAddress: "SAME AS CNEE\n  \n  \n",
    forwardingAgentAddress:
      "BLUE CARGO LOGISTICS CO.,LTD.\n37TH FLOOR, NO.6 SHANDONG ROAD, SHINAN DISTRICT, Q  \n  CHINA\n \n",
    destinationAgentAddress:
      "SEEMANN Y CIA LTDA\nAV. PROVIDENCIA 1650, PROVIDENCIA  \nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:76.583.910-6",
    fowaredBl: "MGA26001853B",
    manifestedPieces: 0,
    manifestedWeight: 0.0,
    paymentType: 1,
    shipmentClass: 1,
    operationFlow: 1,
    shipmentType: 2,
    parentShipmentId: null,
    commodities: [
      {
        commodityType: 1,
        pieces: 15,
        description: "STC\nRGB LIGHTING\nLED STRIPS AND CONTROLLERS",
        totalWeightValue: 200.0,
        totalWeightUOM: 2,
        totalVolumeValue: 2.5,
        totalVolumeUOM: 2,
        packageType: {
          id: 97,
          description: "BOX",
          isShippingContainer: false,
        },
        id: 70008,
      },
    ],
    subShipments: [
      {
        id: 91008,
        number: "MGA26001853B-H1",
        waybillNumber: "MGA26001853B",
        consignee: {
          id: 50001,
          name: "MUNDOGAMING SPA",
        },
        consigneeAddress:
          "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nSANTIAGO CHILE",
        carrier: { id: 27824, name: "QANTAS AIRWAYS" },
        cargoDescription: "F.A.K. - Freight All Kinds",
        manifestedPieces: 15,
        manifestedWeight: 200.0,
        customerReference: "DONGGUAN LIGHTING OC 8423",
        commodities: [
          {
            pieces: 10,
            description: "RGB LED STRIPS 5M",
            totalWeightValue: 130.0,
            totalVolumeValue: 1.6,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
          {
            pieces: 5,
            description: "LIGHTING CONTROLLERS SMART",
            totalWeightValue: 70.0,
            totalVolumeValue: 0.9,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
        ],
      },
    ],
    notes: null,
  },

  // ── Operación 9: En tránsito ──
  {
    id: 90009,
    number: "130-45678919",
    waybillNumber: "MGA26002104A",
    containerNumber: null,
    containerSealNumberOne: null,
    carrier: {
      id: 27825,
      name: "EMIRATES SKYCARGO",
      accountNumber: null,
      code: "176",
      email: null,
    },
    consignee: {
      id: 50001,
      name: "MUNDOGAMING SPA",
      accountNumber: "77.123.456-7",
      code: "MG01",
      email: "contacto@mundogaming.cl",
    },
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    customerReference: "SHENZHEN AUDIO OC 10254",
    cargoDescription: "F.A.K. - Freight All Kinds",
    headload: false,
    hazardous: false,
    departure: {
      type: "SplitDateTime",
      date: "2026-02-16T04:00:00Z",
      time: null,
      displayDate: "02/16/2026",
      displayTime: "",
    },
    arrival: {
      type: "SplitDateTime",
      date: "2026-02-26T04:00:00Z",
      time: null,
      displayDate: "02/26/2026",
      displayTime: "",
    },
    loadingDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    executedOn: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    releaseDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    shipper: {
      id: 60009,
      name: "SHENZHEN AUDIO PRO CO., LTD",
      accountNumber: null,
      code: "AUDIO-5124",
    },
    shipperAddress:
      "SHENZHEN AUDIO PRO CO., LTD\nBLOCK E, 7/F, NO.22 KEYUAN RD, NANSHAN DISTRICT\n518000, SHENZHEN, GUANGDONG, CHINA",
    notifyPartyAddress: "SAME AS CNEE\n  \n  \n",
    forwardingAgentAddress:
      "BLUE CARGO LOGISTICS CO.,LTD.\n37TH FLOOR, NO.6 SHANDONG ROAD, SHINAN DISTRICT, Q  \n  CHINA\n \n",
    destinationAgentAddress:
      "SEEMANN Y CIA LTDA\nAV. PROVIDENCIA 1650, PROVIDENCIA  \nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:76.583.910-6",
    fowaredBl: "MGA26002104A",
    manifestedPieces: 0,
    manifestedWeight: 0.0,
    paymentType: 1,
    shipmentClass: 1,
    operationFlow: 1,
    shipmentType: 2,
    parentShipmentId: null,
    commodities: [
      {
        commodityType: 1,
        pieces: 9,
        description: "STC\nGAMING SPEAKERS\nSURROUND SOUND SYSTEMS",
        totalWeightValue: 180.0,
        totalWeightUOM: 2,
        totalVolumeValue: 1.5,
        totalVolumeUOM: 2,
        packageType: {
          id: 97,
          description: "BOX",
          isShippingContainer: false,
        },
        id: 70009,
      },
    ],
    subShipments: [
      {
        id: 91009,
        number: "MGA26002104A-H1",
        waybillNumber: "MGA26002104A",
        consignee: {
          id: 50001,
          name: "MUNDOGAMING SPA",
        },
        consigneeAddress:
          "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nSANTIAGO CHILE",
        carrier: { id: 27825, name: "EMIRATES SKYCARGO" },
        cargoDescription: "F.A.K. - Freight All Kinds",
        manifestedPieces: 9,
        manifestedWeight: 180.0,
        customerReference: "SHENZHEN AUDIO OC 10254",
        commodities: [
          {
            pieces: 6,
            description: "GAMING SPEAKERS 5.1 SURROUND",
            totalWeightValue: 120.0,
            totalVolumeValue: 1.0,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
          {
            pieces: 3,
            description: "SUBWOOFERS WIRELESS",
            totalWeightValue: 60.0,
            totalVolumeValue: 0.5,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
        ],
      },
    ],
    notes: null,
  },

  // ── Operación 10: Ya llegó ──
  {
    id: 90010,
    number: "131-45678920",
    waybillNumber: "MGA26001854B",
    containerNumber: null,
    containerSealNumberOne: null,
    carrier: {
      id: 27826,
      name: "BRITISH AIRWAYS",
      accountNumber: null,
      code: "125",
      email: null,
    },
    consignee: {
      id: 50001,
      name: "MUNDOGAMING SPA",
      accountNumber: "77.123.456-7",
      code: "MG01",
      email: "contacto@mundogaming.cl",
    },
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    customerReference: "DONGGUAN ACCESS OC 8424",
    cargoDescription: "F.A.K. - Freight All Kinds",
    headload: false,
    hazardous: false,
    departure: {
      type: "SplitDateTime",
      date: "2026-01-25T04:00:00Z",
      time: null,
      displayDate: "01/25/2026",
      displayTime: "",
    },
    arrival: {
      type: "SplitDateTime",
      date: "2026-02-04T04:00:00Z",
      time: null,
      displayDate: "02/04/2026",
      displayTime: "",
    },
    loadingDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    executedOn: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    releaseDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    shipper: {
      id: 60010,
      name: "DONGGUAN ACCESS TECH CO., LTD",
      accountNumber: null,
      code: "ACCESS-3304",
    },
    shipperAddress:
      "DONGGUAN ACCESS TECH CO., LTD\nNO.92 DONGCHENG SOUTH RD, DONGCHENG DISTRICT\n523000, DONGGUAN, GUANGDONG, CHINA",
    notifyPartyAddress: "SAME AS CNEE\n  \n  \n",
    forwardingAgentAddress:
      "BLUE CARGO LOGISTICS CO.,LTD.\n37TH FLOOR, NO.6 SHANDONG ROAD, SHINAN DISTRICT, Q  \n  CHINA\n \n",
    destinationAgentAddress:
      "SEEMANN Y CIA LTDA\nAV. PROVIDENCIA 1650, PROVIDENCIA  \nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:76.583.910-6",
    fowaredBl: "MGA26001854B",
    manifestedPieces: 0,
    manifestedWeight: 0.0,
    paymentType: 1,
    shipmentClass: 1,
    operationFlow: 1,
    shipmentType: 2,
    parentShipmentId: null,
    commodities: [
      {
        commodityType: 1,
        pieces: 20,
        description: "STC\nGAMING ACCESSORIES\nKEYBOARDS, MICE, PADS",
        totalWeightValue: 300.0,
        totalWeightUOM: 2,
        totalVolumeValue: 4.0,
        totalVolumeUOM: 2,
        packageType: {
          id: 97,
          description: "BOX",
          isShippingContainer: false,
        },
        id: 70010,
      },
    ],
    subShipments: [
      {
        id: 91010,
        number: "MGA26001854B-H1",
        waybillNumber: "MGA26001854B",
        consignee: {
          id: 50001,
          name: "MUNDOGAMING SPA",
        },
        consigneeAddress:
          "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nSANTIAGO CHILE",
        carrier: { id: 27826, name: "BRITISH AIRWAYS" },
        cargoDescription: "F.A.K. - Freight All Kinds",
        manifestedPieces: 20,
        manifestedWeight: 300.0,
        customerReference: "DONGGUAN ACCESS OC 8424",
        commodities: [
          {
            pieces: 12,
            description: "MECHANICAL KEYBOARDS RGB",
            totalWeightValue: 180.0,
            totalVolumeValue: 2.4,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
          {
            pieces: 8,
            description: "GAMING MICE WIRELESS",
            totalWeightValue: 120.0,
            totalVolumeValue: 1.6,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
        ],
      },
    ],
    notes: null,
  },

  // ── Operación 11: En tránsito ──
  {
    id: 90011,
    number: "132-45678921",
    waybillNumber: "MGA26002105A",
    containerNumber: null,
    containerSealNumberOne: null,
    carrier: {
      id: 27827,
      name: "KLM CARGO",
      accountNumber: null,
      code: "074",
      email: null,
    },
    consignee: {
      id: 50001,
      name: "MUNDOGAMING SPA",
      accountNumber: "77.123.456-7",
      code: "MG01",
      email: "contacto@mundogaming.cl",
    },
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    customerReference: "SHENZHEN GRAPHICS OC 10255",
    cargoDescription: "F.A.K. - Freight All Kinds",
    headload: false,
    hazardous: false,
    departure: {
      type: "SplitDateTime",
      date: "2026-02-18T04:00:00Z",
      time: null,
      displayDate: "02/18/2026",
      displayTime: "",
    },
    arrival: {
      type: "SplitDateTime",
      date: "2026-02-28T04:00:00Z",
      time: null,
      displayDate: "02/28/2026",
      displayTime: "",
    },
    loadingDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    executedOn: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    releaseDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    shipper: {
      id: 60011,
      name: "SHENZHEN GRAPHICS CARD CO., LTD",
      accountNumber: null,
      code: "GRAPHICS-5125",
    },
    shipperAddress:
      "SHENZHEN GRAPHICS CARD CO., LTD\nBLOCK F, 8/F, NO.23 KEYUAN RD, NANSHAN DISTRICT\n518000, SHENZHEN, GUANGDONG, CHINA",
    notifyPartyAddress: "SAME AS CNEE\n  \n  \n",
    forwardingAgentAddress:
      "BLUE CARGO LOGISTICS CO.,LTD.\n37TH FLOOR, NO.6 SHANDONG ROAD, SHINAN DISTRICT, Q  \n  CHINA\n \n",
    destinationAgentAddress:
      "SEEMANN Y CIA LTDA\nAV. PROVIDENCIA 1650, PROVIDENCIA  \nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:76.583.910-6",
    fowaredBl: "MGA26002105A",
    manifestedPieces: 0,
    manifestedWeight: 0.0,
    paymentType: 1,
    shipmentClass: 1,
    operationFlow: 1,
    shipmentType: 2,
    parentShipmentId: null,
    commodities: [
      {
        commodityType: 1,
        pieces: 5,
        description: "STC\nGRAPHICS CARDS\nHIGH-END GPU CARDS",
        totalWeightValue: 100.0,
        totalWeightUOM: 2,
        totalVolumeValue: 0.8,
        totalVolumeUOM: 2,
        packageType: {
          id: 97,
          description: "BOX",
          isShippingContainer: false,
        },
        id: 70011,
      },
    ],
    subShipments: [
      {
        id: 91011,
        number: "MGA26002105A-H1",
        waybillNumber: "MGA26002105A",
        consignee: {
          id: 50001,
          name: "MUNDOGAMING SPA",
        },
        consigneeAddress:
          "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nSANTIAGO CHILE",
        carrier: { id: 27827, name: "KLM CARGO" },
        cargoDescription: "F.A.K. - Freight All Kinds",
        manifestedPieces: 5,
        manifestedWeight: 100.0,
        customerReference: "SHENZHEN GRAPHICS OC 10255",
        commodities: [
          {
            pieces: 5,
            description: "GRAPHICS CARDS RTX 5090",
            totalWeightValue: 100.0,
            totalVolumeValue: 0.8,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
        ],
      },
    ],
    notes: null,
  },

  // ── Operación 12: Ya llegó ──
  {
    id: 90012,
    number: "133-45678922",
    waybillNumber: "MGA26001855B",
    containerNumber: null,
    containerSealNumberOne: null,
    carrier: {
      id: 27828,
      name: "SINGAPORE AIRLINES CARGO",
      accountNumber: null,
      code: "618",
      email: null,
    },
    consignee: {
      id: 50001,
      name: "MUNDOGAMING SPA",
      accountNumber: "77.123.456-7",
      code: "MG01",
      email: "contacto@mundogaming.cl",
    },
    consigneeAddress:
      "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:77.123.456-7",
    customerReference: "DONGGUAN STORAGE OC 8425",
    cargoDescription: "F.A.K. - Freight All Kinds",
    headload: false,
    hazardous: false,
    departure: {
      type: "SplitDateTime",
      date: "2026-01-28T04:00:00Z",
      time: null,
      displayDate: "01/28/2026",
      displayTime: "",
    },
    arrival: {
      type: "SplitDateTime",
      date: "2026-02-07T04:00:00Z",
      time: null,
      displayDate: "02/07/2026",
      displayTime: "",
    },
    loadingDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    executedOn: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    releaseDate: {
      type: null,
      date: null,
      time: null,
      displayDate: null,
      displayTime: null,
    },
    shipper: {
      id: 60012,
      name: "DONGGUAN STORAGE SOLUTIONS CO., LTD",
      accountNumber: null,
      code: "STORAGE-3305",
    },
    shipperAddress:
      "DONGGUAN STORAGE SOLUTIONS CO., LTD\nNO.93 DONGCHENG SOUTH RD, DONGCHENG DISTRICT\n523000, DONGGUAN, GUANGDONG, CHINA",
    notifyPartyAddress: "SAME AS CNEE\n  \n  \n",
    forwardingAgentAddress:
      "BLUE CARGO LOGISTICS CO.,LTD.\n37TH FLOOR, NO.6 SHANDONG ROAD, SHINAN DISTRICT, Q  \n  CHINA\n \n",
    destinationAgentAddress:
      "SEEMANN Y CIA LTDA\nAV. PROVIDENCIA 1650, PROVIDENCIA  \nREGION METROPOLITANA, SANTIAGO CHILE\nTAX-ID:76.583.910-6",
    fowaredBl: "MGA26001855B",
    manifestedPieces: 0,
    manifestedWeight: 0.0,
    paymentType: 1,
    shipmentClass: 1,
    operationFlow: 1,
    shipmentType: 2,
    parentShipmentId: null,
    commodities: [
      {
        commodityType: 1,
        pieces: 25,
        description: "STC\nSSD DRIVES\nHIGH-SPEED SOLID STATE DRIVES",
        totalWeightValue: 350.0,
        totalWeightUOM: 2,
        totalVolumeValue: 4.5,
        totalVolumeUOM: 2,
        packageType: {
          id: 97,
          description: "BOX",
          isShippingContainer: false,
        },
        id: 70012,
      },
    ],
    subShipments: [
      {
        id: 91012,
        number: "MGA26001855B-H1",
        waybillNumber: "MGA26001855B",
        consignee: {
          id: 50001,
          name: "MUNDOGAMING SPA",
        },
        consigneeAddress:
          "MUNDOGAMING SPA\nAV. APOQUINDO 4700, OF. 1501, LAS CONDES\nSANTIAGO CHILE",
        carrier: { id: 27828, name: "SINGAPORE AIRLINES CARGO" },
        cargoDescription: "F.A.K. - Freight All Kinds",
        manifestedPieces: 25,
        manifestedWeight: 350.0,
        customerReference: "DONGGUAN STORAGE OC 8425",
        commodities: [
          {
            pieces: 15,
            description: "SSD DRIVES 2TB NVME",
            totalWeightValue: 210.0,
            totalVolumeValue: 3.0,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
          {
            pieces: 10,
            description: "SSD DRIVES 1TB SATA",
            totalWeightValue: 140.0,
            totalVolumeValue: 1.5,
            packageType: { id: 97, description: "BOX", isShippingContainer: false },
          },
        ],
      },
    ],
    notes: null,
  },
];
